# Timeout in seconds
# Wait 5 seconds on the menu before auto-selecting the first entry
TIMEOUT=5

# Boot entry label
:Zig OS
# Use limine protocol
PROTOCOL=limine
KERNEL_PATH=boot:///kernel.elf
KERNEL_CMDLINE=root=/dev/null
