// kernel/bootloader/bootloader.zig
//
// Bootloader abstraction layer.
// Defines the generic types the kernel uses to describe boot-time information,
// and dispatches init() to the correct bootloader implementation at compile time.
//
// Nothing above this file knows which bootloader loaded the kernel.
// To add a new bootloader: add a case to the impl switch, create
// bootloader/<name>/init.zig that returns a BootInfo, and add the variant
// to the Bootloader enum in build.zig.

// build_options is a module generated by build.zig at compile time.
// It contains the values passed via -D flags (e.g. -Dbootloader=limine).
// Importing it here gives us a comptime constant we can switch on.
const build_options = @import("build_options");

// Comptime bootloader dispatch.
// The switch is evaluated entirely at compile time: only one branch is compiled
// into the final binary. `impl` ends up being the selected init.zig module,
// and calls through it are resolved at compile time — no vtable, no indirection.
// The compiler will error if build_options.bootloader holds a value with no case here,
// which makes adding a new bootloader a compile-time checklist item, not a runtime risk.
const impl = switch (build_options.bootloader) {
    .limine => @import("limine/init.zig"),
};

/// Classification of a physical memory region.
/// Each bootloader uses its own names and numeric values for region types;
/// this enum is the kernel's single vocabulary for all of them.
/// init.zig for each bootloader is responsible for mapping its own tags to these.
pub const MemoryRegionKind = enum {
    usable,
    reserved,
    acpi_reclaimable,
    acpi_nvs,
    bad_memory,
    bootloader_reclaimable,
    executable_and_modules,
    framebuffer,
};

/// A single entry from the physical memory map.
/// base and length are both in bytes; base is a physical address.
/// The physical frame allocator (Phase 5) iterates these to find frames it can hand out.
pub const MemoryRegion = struct {
    base: u64,
    length: u64,
    kind: MemoryRegionKind,
};

/// Everything the kernel needs to know about the linear framebuffer.
/// address is the physical address of pixel (0, 0).
/// pitch is the number of bytes per row — not always equal to width * (bpp / 8)
/// because the firmware may add padding at the end of each row.
pub const FramebufferInfo = struct {
    address: u64,
    width: u64,
    height: u64,
    pitch: u64,
    bpp: u16,
};

// Fixed-size memory region table — no allocator needed at this stage.
// 256 slots covers every real memory map Limine or GRUB will ever produce.
pub const max_memory_regions = 256;

/// The single struct _start receives from the bootloader.
/// All fields use kernel-defined types — no bootloader types leak past init().
/// memory_region_count tells callers how many entries in memory_regions are valid;
/// the remainder of the fixed array is uninitialized and must not be read.
pub const BootInfo = struct {
    hhdm_offset: u64,
    framebuffer: ?FramebufferInfo,
    memory_regions: [max_memory_regions]MemoryRegion,
    memory_region_count: usize,
};

/// Called once from _start. Delegates to the bootloader implementation selected
/// at compile time, which reads the bootloader's native response structures and
/// returns a fully translated BootInfo.
pub fn init() BootInfo {
    return impl.init();
}
